name: "CI"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "pnpm"
          node-version: "16"

      - name: "Install the dependencies"
        run: "pnpm install --frozen-lockfile"

      - name: "Lint the code"
        run: "pnpm lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
